# Generated by Django 4.2.29 on 2026-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('phone_booking', 'Требуется звонок клиенту'), ('cancellation', 'Требуется уведомить об отмене'), ('system', 'Системное уведомление')], default='phone_booking', max_length=20),
        ),
    ]
