# Generated by Django 4.2.29 on 2026-04-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_adminnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Изображение номера'),
        ),
    ]
