# Generated by Django 4.2.29 on 2026-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID бронирования'),
        ),
    ]
